import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import styled from 'styled-components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by AK The Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultContainer>
        <Sidebar />
        <DefaultHome>
          <InfoBox>
            <h3
              style={{
                margin: '2rem 15rem -13px 15rem',
                fontSize: '2.5rem',
                border: '3.5px solid',
                borderImageSlice: 1,
                borderImageSource: 'linear-gradient(to left, #743ad5, #d53a9d)',
                display: 'inline-block',
                padding: '.6rem',
              }}
            >
              Hi There ! 👋👋👋
            </h3>
            <h4
              style={{
                margin: '4rem 3rem 0 3rem',
                fontSize: '2rem',
                borderBottom: '1px solid gray',
                paddingBottom: '.7rem',
                letterSpacing: '.6px',
              }}
            >
              Current Features :
            </h4>
            <ul
              style={{
                fontSize: 15.5,
                color: '#343A40',
                margin: '1.5rem 0 0 5.5rem',
                lineHeight: 1.6,
              }}
            >
              <li>Login & Logout</li>
              <li>Add Chat</li>
              <li>Search Chat</li>
              <li>Chat with individual user</li>
              <li>Send Emoji&apos;s</li>
              <li>Auto scroll to last message</li>
            </ul>
            <h4
              style={{
                margin: '2.5rem 3rem 0 3rem',
                fontSize: '2rem',
                borderBottom: '1px solid gray',
                paddingBottom: '.7rem',
                letterSpacing: '.6px',
              }}
            >
              Upcoming Features :
            </h4>
            <ul
              style={{
                fontSize: 15.5,
                color: '#343A40',
                margin: '1.5rem 0 0 5.5rem',
                lineHeight: 1.6,
              }}
            >
              <li>Typing Indication</li>
              <li>Date Wise Chat Splitup</li>
              <li>Delete Chat</li>
              <li>Sort Chat list by recent message</li>
              <li>Mobile version</li>
            </ul>
          </InfoBox>
        </DefaultHome>
      </DefaultContainer>
    </div>
  );
}

const DefaultContainer = styled.div`
  display: flex;
`;

const DefaultHome = styled.div`
  display: flex;
  flex: 1;
  height: 100vh;
  justify-content: center;
  align-items: center;
`;

const InfoBox = styled.div`
  height: 50rem;
  width: 55rem;
  background-color: #99d98c;
  font-weight: 500;
  font-size: 1.4rem;
  border-radius: 1rem;
  box-shadow: 0 20px 30px 0 rgba(0, 0, 0, 0.19);
`;
