import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import styled from 'styled-components';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by AK The Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultContainer>
        <Sidebar />
        <DefaultHome>
          <InfoBox>
            <h3
              style={{
                margin: '2rem 15rem -13px 15rem',
                fontSize: '2.5rem',
                border: '3.5px solid',
                borderImageSlice: 1,
                borderImageSource: 'linear-gradient(to left, #743ad5, #d53a9d)',
                display: 'inline-block',
                padding: '.6rem',
              }}
            >
              Hi There ! 👋👋👋
            </h3>
            <h4
              style={{
                margin: '4rem 3rem 0 3rem',
                fontSize: '2rem',
                borderBottom: '1px solid gray',
                paddingBottom: '.7rem',
                letterSpacing: '.6px',
              }}
            >
              Current Features :
            </h4>
            <ul
              style={{
                fontSize: 15.5,
                color: '#343A40',
                margin: '1.5rem 0 0 5.5rem',
                lineHeight: 1.6,
              }}
            >
              <li>Login & Logout</li>
              <li>Add Chat</li>
              <li>Search Chat</li>
              <li>Delete Chat</li>
              <li>Chat with individual user</li>
              <li>Send Emoji&apos;s</li>
              <li>Auto scroll to last message</li>
              <li>
                <a
                  href="https://github.com/Ajay-056/Whatsapp-Clone-NextJS/tags"
                  target="_blank"
                  rel="noreferrer"
                >
                  Click here to see the release change log...
                </a>
              </li>
            </ul>
            <h4
              style={{
                margin: '2.5rem 3rem 0 3rem',
                fontSize: '2rem',
                borderBottom: '1px solid gray',
                paddingBottom: '.7rem',
                letterSpacing: '.6px',
              }}
            >
              Upcoming Features :
            </h4>
            <ul
              style={{
                fontSize: 15.5,
                color: '#343A40',
                margin: '1.5rem 0 0 5.5rem',
                lineHeight: 1.6,
              }}
            >
              <li>Typing Indication</li>
              <li>Date Wise Chat Splitup</li>
              <li>Sort Chat list by recent message</li>
              <li>Mobile version</li>
            </ul>
            <p
              style={{
                borderBottom: '1px solid gray',
                margin: '2.5rem 3rem 0 3rem',
              }}
            ></p>
            <p
              style={{
                textAlign: 'center',
                display: 'flex',
                marginTop: '1rem',
                justifyContent: 'space-evenly',
                alignItems: 'center',
              }}
            >
              <a
                href="https://github.com/Ajay-056/Whatsapp-Clone-NextJS"
                target="_blank noreferrer"
                onClick={() =>
                  alert('Are You Sure want to leave without logout?')
                }
              >
                <Image
                  src="/icons8-github.svg"
                  alt="github"
                  height={40}
                  width={40}
                />
              </a>
              <a
                href="https://www.twitter.com/balaajay19"
                target="_blank noreferrer"
                onClick={() =>
                  alert('Are You Sure want to leave without logout?')
                }
              >
                <Image
                  src="/icons8-twitter-48.png"
                  alt="twitter"
                  height={40}
                  width={40}
                />
              </a>
              <a
                href="https://www.linkedin.com/in/ajay-krishna-065a1a162"
                target="_blank noreferrer"
                onClick={() =>
                  alert('Are You Sure want to leave without logout?')
                }
              >
                <Image
                  src="/icons8-linkedin-48.png"
                  alt="linkedin"
                  height={40}
                  width={40}
                />
              </a>
            </p>
          </InfoBox>
        </DefaultHome>
      </DefaultContainer>
    </div>
  );
}

const DefaultContainer = styled.div`
  display: flex;
`;

const DefaultHome = styled.div`
  display: flex;
  flex: 1;
  height: 100vh;
  justify-content: center;
  align-items: center;
`;

const InfoBox = styled.div`
  height: 60rem;
  width: 56rem;
  background-color: #99d98c;
  font-weight: 500;
  font-size: 1.4rem;
  border-radius: 1rem;
  box-shadow: 0 20px 30px 0 rgba(0, 0, 0, 0.19);
`;
